name: Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Ansible
      run: sudo apt-get install -y ansible  # Install Ansible on the GitHub Actions runner

    - name: Install community.aws collection
      run: ansible-galaxy collection install community.aws

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0  # Specify the desired Terraform version
        
    - name: Run Ansible Playbook to provision EC2 instance
      run: |
        ansible-playbook ansible/playbook.yml
