name: Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0  
        
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
        
    - name: Terraform Init and Apply
      working-directory: terraform
      run: |
        terraform init
        terraform apply -auto-approve
      
    - name: Setup Ansible
      run: sudo yum install -y ansible  

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ../ansible/my-key-pair.pem ec2-user@ ansible/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
