name: Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0  # Specify the desired Terraform version
        
    - name: Terraform Init and Apply
      working-directory: terraform
      run: |
        terraform init
        terraform apply -auto-approve
      
    - name: Setup Ansible
      run: sudo apt-get install -y ansible  # Install Ansible on the GitHub Actions runner

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i '${{ steps.build.outputs.public_ip }},' ansible/configure_ec2.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
